export const layouts = {
  consonants: [
    [ // row 1, nasal
      ['blanc', 'm'],
      ['blanc', 'ɱ'],
      ['blanc', 'n'],
      ['blanc', 'ɳ'],
      ['blanc', 'ɲ'],
      ['blanc', 'ŋ'],
      ['blanc', 'ɴ'],
      'disabled',
      'disabled',
    ],
    [ // row 2, plosive
      ['p', 'b'],
      'blanc',
      ['t', 'd'],
      ['ʈ', 'ɖ'],
      ['c', 'ɟ'],
      ['k', 'g'],
      ['q', 'ɢ'],
      ['ʡ', 'disabled'],
      ['ʔ', 'disabled'],
    ],
    [ // row 3, sibilant fricative
      'disabled',
      'disabled',
      ['s', 'z'],
      ['ʃ', 'ʒ'],
      ['ʂ', 'ʐ'],
      ['ɕ', 'ʑ'],
      'disabled',
      'disabled',
      'disabled',
      'disabled',
    ],
    [ // row 4, non-sibilant fricative
      ['ɸ', 'β'],
      ['f', 'v'],
      ['θ', 'ð'],
      'blanc',
      'blanc',
      'blanc',
      ['ç', 'ʝ'],
      ['x', 'ɣ'],
      ['χ', 'ʁ'],
      ['ħ', 'ʕ'],
      ['h', 'ɦ'],
    ],
    [ // row 5, approximant
      'blanc',
      ['blanc', 'ʋ'],
      ['blanc', 'ɹ'],
      ['blanc', 'ɻ'],      
      ['blanc', 'j'],
      ['blanc', 'ɰ'],
      'blanc',
      'blanc',
      'blanc',
    ],
    [ // row 6, tap/flap
      'blanc',
      ['blanc', 'ⱱ'],
      ['blanc', 'ɾ'],
      ['blanc', 'ɽ'],      
      'blanc',
      'disabled',
      'blanc',
      'blanc',
      'blanc',
    ],
    [ // row 7, trill
      ['blanc', 'ʙ'],
      'blanc',
      ['blanc', 'r'],
      'blanc',    
      'blanc',
      'disabled',
      ['blanc', 'ʀ'],
      ['ʜ', 'ʢ'],
      'blanc',
    ],
  ],
}