export const layouts = {
  consonants: [
    [ // row 1, nasal
      [['m\u0325', 'lp1m1-n_v'], ['m', 'lp1m1-n']],
      [['ɱ\u030a', 'lp2m1-n_v'], ['ɱ', 'lp2m1-n']],
      [['n\u0325', 'cm1-n_v'], ['n', 'cm1-n']],
      [['ɳ\u030a', 'cp2p3m1-n_v'], ['ɳ', 'cp2p3m1-n']],
      [['ɲ\u030a', 'dp1m1-n_v'], ['ɲ', 'dp1m1-n']],
      [['ŋ\u030a', 'dp2m1-n_v'], ['ŋ', 'dp2m1-n']],
      [['ɴ\u030a', 'dp3m1-n_v'], ['ɴ', 'dp3m1-n']],
      'disabled',
      'disabled',
    ],
    [ // row 2, plosive
      ['p', 'b'],
      'blanc',
      ['t', 'd'],
      ['ʈ', 'ɖ'],
      ['c', 'ɟ'],
      ['k', 'g'],
      ['q', 'ɢ'],
      ['ʡ', 'disabled'],
      ['ʔ', 'disabled'],
    ],
    [ // row 3, sibilant fricative
      'disabled',
      'disabled',
      ['s', 'z'],
      ['ʃ', 'ʒ'],
      ['ʂ', 'ʐ'],
      ['ɕ', 'ʑ'],
      'disabled',
      'disabled',
      'disabled',
      'disabled',
    ],
    [ // row 4, non-sibilant fricative
      ['ɸ', 'β'],
      ['f', 'v'],
      ['θ', 'ð'],
      'blanc',
      'blanc',
      'blanc',
      ['ç', 'ʝ'],
      ['x', 'ɣ'],
      ['χ', 'ʁ'],
      ['ħ', 'ʕ'],
      ['h', 'ɦ'],
    ],
    [ // row 5, approximant
      'blanc',
      ['blanc', 'ʋ'],
      ['blanc', 'ɹ'],
      ['blanc', 'ɻ'],      
      ['blanc', 'j'],
      ['blanc', 'ɰ'],
      'blanc',
      'blanc',
      'blanc',
    ],
    [ // row 6, tap/flap
      'blanc',
      ['blanc', 'ⱱ'],
      ['blanc', 'ɾ'],
      ['blanc', 'ɽ'],      
      'blanc',
      'disabled',
      'blanc',
      'blanc',
      'blanc',
    ],
    [ // row 7, trill
      ['blanc', 'ʙ'],
      'blanc',
      ['blanc', 'r'],
      'blanc',    
      'blanc',
      'disabled',
      ['blanc', 'ʀ'],
      ['ʜ', 'ʢ'],
      'blanc',
    ],
  ],
}