const querty = [
  [
    'disabled',
    ['q', 'Q'],
    ['w', 'W'],
    ['e', 'E'],
    ['r', 'R'],
    ['t', 'T'],
    ['y', 'Y'],
    ['u', 'U'],
    ['i', 'I'],
    ['o', 'O'],
    ['p', 'P'],
    'disabled',
    'disabled',
    'disabled',
  ],
  [
    'disabled',
    ['a', 'A'],
    ['s', 'S'],
    ['d', 'D'],
    ['f', 'F'],
    ['g', 'G'],
    ['h', 'H'],
    ['j', 'J'],
    ['k', 'K'],
    ['l', 'L'],
    'disabled',
    'disabled',
    'disabled',
  ],
  [
    [],
    ['z', 'Z'],
    ['x', 'X'],
    ['c', 'C'],
    ['v', 'V'],
    ['b', 'B'],
    ['n', 'N'],
    ['m', 'M'],
    'disabled',
    'disabled',
    'disabled',
    'disabled',
  ]
]

const dvorak = [
  [
    'disabled',
    'disabled',
    'disabled',
    'disabled',
    ['p', 'P'],
    ['y', 'Y'],
    ['f', 'F'],
    ['g', 'G'],
    ['c', 'C'],
    ['r', 'R'],
    ['l', 'L'],
    'disabled',
    'disabled',
    'disabled',
  ],
  [
    'disabled',
    ['a', 'A'],
    ['o', 'O'],
    ['e', 'E'],
    ['u', 'U'],
    ['i', 'I'],
    ['d', 'D'],
    ['h', 'H'],
    ['t', 'T'],
    ['n', 'N'],
    ['s', 'S'],
    'disabled',
    'disabled',
  ],
  [
    [],
    'disabled',
    ['q', 'Q'],
    ['j', 'J'],
    ['k', 'K'],
    ['x', 'X'],
    ['b', 'B'],
    ['m', 'M'],
    ['w', 'W'],
    ['v', 'V'],
    ['z', 'Z'],
    'disabled',
  ]
]

const ipe = [
  [
    'disabled',
    ['q', 'Q'],
    ['w', 'W'],
    ['e', 'E'],
    ['r', 'R'],
    ['t', 'T'],
    ['y', 'Y'],
    ['u', 'U'],
    ['i', 'I'],
    ['o', 'O'],
    ['p', 'P'],
    'disabled',
    'disabled',
    'disabled',
  ],
  [
    'disabled',
    ['a', 'A'],
    ['s', 'S'],
    ['d', 'D'],
    ['f', 'F'],
    ['g', 'G'],
    ['h', 'H'],
    ['j', 'J'],
    ['k', 'K'],
    ['l', 'L'],
    ['\u0304', '\u0308'],
    ['\u0301', '\u0300'],
    'disabled',
  ],
  [
    [],
    ['z', 'Z'],
    ['x', 'X'],
    ['c', 'C'],
    ['v', 'V'],
    ['b', 'B'],
    ['n', 'N'],
    ['m', 'M'],
    ['\u02D8', '\u0306'],
    ['\u0302'],
    ['\u0327'],
    'disabled',
  ]
]

export const layouts = {querty, dvorak, ipe}